### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by Romz24** [LolHens/mc-fluid-physics#15] opened 2020-10-25 11:53 UTC
From time to time my server crashes and it seems to be related to your mod.

**Minecraft version:** 1.16.3
**Mod version:** 1.3.4+fabric-1.16.2
**Fabric API:** 0.24.1+build.412-1.16
**Fabric loader:** 0.10.1+build.209 and 0.10.3+build.211

[crash-2020-10-22_18.31.00-server.txt](https://github.com/LolHens/mc-fluid-physics/files/5434650/crash-2020-10-22_18.31.00-server.txt)
[crash-2020-10-25_06.46.00-server.txt](https://github.com/LolHens/mc-fluid-physics/files/5434651/crash-2020-10-25_06.46.00-server.txt)

**Comment by LolHens** [comment] 2020-10-25 13:53
I think that you are running out of memory because, allthough these crashes happen in this mod, they are always caused by java trying to allocate more memory.
Could you check your available RAM?
In Java there is also an option called "-Xmx" which controls how many of your actual memory can be used by java. Maybe it is misconfigured.
I will probably add an option to limit the amount of memory that can be consumed by the fluid source finder.

**Comment by Romz24** [comment] 2020-10-25 14:03
My server has 16GB of RAM, very strange that this is not enough.

![image](https://user-images.githubusercontent.com/2458113/97109356-e036b100-16e3-11eb-958e-23babaeb4de6.png)

**Comment by LolHens** [comment] 2020-10-25 14:47
Thanks for confirming!
I just made a new version which limits the number of blocks checked by default.
https://github.com/LolHens/mc-fluid-physics/releases/tag/1.3.6

Should be ready in about 15 minutes.
I also saw that you were using lithium. I haven't tested this mod with lithium on 1.16.3 yet which is what I'll probably do next.

**Comment by Romz24** [comment] 2020-10-25 14:58
Thanks for the quick response

**Comment by Romz24** [comment] 2020-10-25 15:21
Updated the mod, and crashed again. And this looks like a different problem (but it is not certain). But the problem is clearly related to your mod, judging by the log.

[crash-2020-10-25_18.18.42-server.txt](https://github.com/LolHens/mc-fluid-physics/files/5434960/crash-2020-10-25_18.18.42-server.txt)

**Comment by LolHens** [comment] 2020-10-25 17:34
Okay I'll test a bit more with lithium.

**Comment by Romz24** [comment] 2020-10-25 17:51
You think the problem is **lithium**?

**Comment by LolHens** [comment] 2020-10-25 17:55
well not directly. It might be an incompatibility because lithium is one of the more invasive mods allthough it is usually pretty stable but I saw it in the crashlog and that it replaces some of minecrafts underlying functions for performance reasons. I have not yet seen anyone else run into this crash so it might be a little harder for me to reproduce.

**Comment by Romz24** [comment] 2020-10-25 17:57
In fact, the problem is complex, it can crash the server immediately, or maybe after a long time. I will try to remove lithium, see how it works without it.

**Comment by Romz24** [comment] 2020-10-25 18:09
So, a very strange situation. I removed lithium, the server crashes after starting after a few seconds.

[crash-2020-10-25_21.05.10-server.txt](https://github.com/LolHens/mc-fluid-physics/files/5435596/crash-2020-10-25_21.05.10-server.txt)

**Comment by Romz24** [comment] 2020-10-26 05:08
Today I tested it again in more detail, having previously removed the mods **lithium** and **phosphor**, the problem remained. The server still crashes after a while. And the problem is definitely not related to memory, at the time of the fall, the server uses within 4GB


[crash-2020-10-26_08.02.16-server.txt](https://github.com/LolHens/mc-fluid-physics/files/5436906/crash-2020-10-26_08.02.16-server.txt)

**Comment by LolHens** [comment] 2020-10-26 10:03
still this obfuscated java.lang,Error. Could you upload your logs/latest.log?

**Comment by LolHens** [comment] 2020-10-30 15:24
I have tested this with the same versions and mods and sadly could not yet reproduce this Error.

**Comment by Romz24** [comment] 2020-10-30 16:06
I have currently removed the mod from the build. I can say that it is difficult to achieve a crash in a regular game, and it takes a long time. To get a more or less fast crash, I tried to detonate nuclear bombs in the ocean from the Modern Industrialization mod

**Comment by LolHens** [comment] 2021-04-16 08:23
I'll close this for now but we can reopen this any time.

**Closed by LolHens** 2021-04-16 08:23 UTC
